### ISSUE TITLE
Bad output of latexmk --version

### ISSUE THREAD

**Issue by nrbeaton** [djsutherland/arxiv-collector#11]
I swear this worked a month or two ago (running on MacOS Catalina) but now `arxiv-collector main.tex` produces the following error:

```
Traceback (most recent call last):
  File "/Users/nrbeaton/anaconda3/bin/arxiv-collector", line 10, in <module>
    sys.exit(main())
  File "/Users/nrbeaton/anaconda3/lib/python3.6/site-packages/arxiv_collector.py", line 353, in main
    version = get_latexmk_version(args.latexmk)
  File "/Users/nrbeaton/anaconda3/lib/python3.6/site-packages/arxiv_collector.py", line 77, in get_latexmk_version
    raise ValueError("Bad output of {} --version:\n{}".format(latexmk, out))
ValueError: Bad output of latexmk --version:
b'\nLatexmk, John Collins, 26 Dec. 2019. Version 4.67\n'
```

**Comment by djsutherland** [comment]
Looks like the newest version of latexmk tweaked the version output format. Should be a trivial fix; I'll publish it when I get home in an hour or two. :+1:
