### ISSUE TITLE
ascii input as UTF-8 doesn't exist

### ISSUE THREAD

**Issue by bisraelsen** [djsutherland/arxiv-collector#7]
Trying to use the script on a document in ubuntu. Compiling using `latexmk -pdf [main.tex]` works. When I run `arxiv-collector main.tex` I get the following error:

```
(xenial)brett@localhost:~/Downloads/SC_Conference$ arxiv-collector main.tex
Building main...
Traceback (most recent call last):
  File "/home/brett/.local/bin/arxiv-collector", line 11, in <module>
    sys.exit(main())
  File "/home/brett/.local/lib/python3.5/site-packages/arxiv_collector.py", line 174, in main
    strip_comments=args.strip_comments, verbosity=args.verbosity)
  File "/home/brett/.local/lib/python3.5/site-packages/arxiv_collector.py", line 109, in collect
    add(dep)
  File "/home/brett/.local/lib/python3.5/site-packages/arxiv_collector.py", line 68, in add
    raise OSError("{} doesn't exist!".format(path))
OSError: ascii input as UTF-8 doesn't exist!
```

I'm not exactly sure what the error means. Are you expecting all files to be encoded as `UTF-8`?

**Comment by bisraelsen** [comment]
@dougalsutherland any ideas?

**Comment by djsutherland** [comment]
@bisraelsen Sorry for the delay; my github notifications are a travesty.

The error message is kind of a funny coincidence; it looks like `latexmk` is outputting the line `ascii input as UTF-8` in the dependencies section for some reason, and so `arxiv-collector` is looking for a file named `ascii input as UTF-8`, which doesn't exist. The overall message then ends up being, confusingly, quasi-grammatical.

I don't think I've seen this before. Can you post the full output of `latexmk -pdf -silent -deps main.tex`, specifically between the `#===Dependents` and `#===End dependents` lines?

**Comment by bisraelsen** [comment]
@dougalsutherland, 

Here you go:
```
(xenial)brett@localhost:~/GitProjects/SC_Conference$ latexmk -pdf -silent -deps main.tex 
Latexmk: Run number 1 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Non-existent bbl file 'main.bbl'
 No file main.bbl.
Latexmk: Summary of warnings:
  Latex failed to resolve 11 reference(s)
  Latex failed to resolve 24 citation(s)
#===Dependents, and related info, for main.tex:
main.pdf :\
    /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/texfonts.map\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmbsy5.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmbsy6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmbsy7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmbsy9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmex7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmex9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmmib5.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmmib6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmmib7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmmib9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam5.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm5.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbsy10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx12.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx5.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx7.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbx9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmbxti10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmmi6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmmi9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmmib10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmr12.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmr6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmr9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmsy6.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmsy9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmti10.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/tfm/public/cm/cmtt9.tfm\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx9.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmbxti10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmex10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi5.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi6.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi7.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi8.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi9.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr6.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr7.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr8.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr9.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy5.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy6.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy7.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy9.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmti10.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmtt9.pfb\
    /usr/local/texlive/2017/texmf-dist/fonts/type1/public/amsfonts/symbols/msbm10.pfb\
    /usr/local/texlive/2017/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\
    /usr/local/texlive/2017/texmf-dist/tex/generic/ifxetex/ifxetex.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/etexcmds.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifluatex.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifpdf.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifvtex.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/infwarerr.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ltxcmds.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryarrows.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarybackgrounds.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarycalc.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarypatterns.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarypositioning.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryshapes.geometric.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/libraries/pgflibraryarrows.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/libraries/pgflibrarypatterns.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/libraries/shapes/pgflibraryshapes.geometric.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfcalendar.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex\
    /usr/local/texlive/2017/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def\
    /usr/local/texlive/2017/texmf-dist/tex/generic/xstring/xstring.sty\
    /usr/local/texlive/2017/texmf-dist/tex/generic/xstring/xstring.tex\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amscls/amsthm.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsfonts/amsfonts.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsfonts/amssymb.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsfonts/umsa.fd\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsfonts/umsb.fd\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amsbsy.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amsgen.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amsmath.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amsopn.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/amsmath/amstext.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/ifthen.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/omscmr.fd\
    /usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/bbx/numeric.bbx\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/bbx/standard.bbx\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/blx-compat.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/blx-dm.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/cbx/numeric.cbx\
    /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/lbx/english.lbx\
    /usr/local/texlive/2017/texmf-dist/tex/latex/booktabs/booktabs.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/caption/caption.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/caption/caption3.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/caption/subcaption.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/carlisle/remreset.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/enumitem/enumitem.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/etoolbox/etoolbox.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/geometry/geometry.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics-cfg/color.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics-cfg/graphics.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics-def/pdftex.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics/graphics.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics/graphicx.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics/keyval.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/graphics/trig.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg\
    /usr/local/texlive/2017/texmf-dist/tex/latex/logreq/logreq.def\
    /usr/local/texlive/2017/texmf-dist/tex/latex/logreq/logreq.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/mathtools/mathtools.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/mathtools/mhsetup.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/ms/everyshi.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/aliascnt.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/grfext.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/oberdiek/kvoptions.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/math/pgfmath.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/utilities/pgfcalendar.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/utilities/pgffor.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/pgfgantt/pgfgantt.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/tabulary/tabulary.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/tools/array.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/tools/bm.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/tools/calc.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/tools/multicol.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/url/url.sty\
    /usr/local/texlive/2017/texmf-dist/tex/latex/xcolor/xcolor.sty\
    /usr/local/texlive/2017/texmf-dist/web2c/texmf.cnf\
    /usr/local/texlive/2017/texmf-var/fonts/map/pdftex/updmap/pdftex.map\
    /usr/local/texlive/2017/texmf-var/web2c/pdftex/pdflatex.fmt\
    /usr/local/texlive/2017/texmf.cnf\
    FaMSeC.tex\
    FaMSeC_math_commands.tex\
    Figures/FaMSeC.png\
    Figures/RoadNet.pdf\
    Figures/experiment_screenshot_Compressed.png\
    Figures/p1.pdf\
    Figures/p1_table.pdf\
    Figures/scTrendsBoundaryExample_2generic.png\
    Figures/total_score.pdf\
    Figures/xO_FullADT.png\
    Figures/xQ_combined.png\
    background.tex\
    conclusions.tex\
    experiment_results.tex\
    introduction.tex\
    llncs.cls\
    main.tex\
    methodology.tex\
    newSolverQualitySection.tex
#===End dependents for main.tex:
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'main.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

**Comment by djsutherland** [comment]
I'm very confused by this output. Could you upload the source somewhere so I can fiddle with it? (Either a minimized version that shows the same problem or just the whole thing.)

**Comment by bisraelsen** [comment]
it here: https://github.com/bisraelsen/SC_Conference

**Comment by djsutherland** [comment]
Yeah, this works fine for me locally (as I would expect from your output above). Can you give a little more details about the system where this failed on? Does it still fail on the current release? If so, can you post the output of `arxiv-collector --debug`?
